config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  validates_presence_of :title

  # === CLASS METHODS =====

  def self.all_boards(user_id)
    Board.find_by_sql("
      SELECT *
      FROM boards
      WHERE boards.user_id = #{user_id}
      ")
  end

  def self.single_board(user_id, board_id)
    Board.find_by_sql(["
      SELECT *
      FROM boards
      WHERE boards.user_id = ? AND boards.id = ?
      ", user_id, board_id]).first
  end

  def self.create_board(user_id, board_params)
    Board.find_by_sql(["
      INSERT INTO boards(title, user_id, created_at, updated_at)
      VALUES (:title, :user_id, :created_at, :updated_at)",
      {
        title: board_params[:title],
        user_id: user_id,
        created_at: DateTime.now,
        updated_at: DateTime.now
      }
      ])
  end

  def self.update_board(board_id, board_params)
    Board.find_by_sql (["
      UPDATE boards
      SET title = ?, updated_at = ?
      WHERE boards.id = ?
      ", board_params[:title], DateTime.now, board_id])
    end
    
  def self.delete_board(board_id)
    Board.find_by_sql(["
      DELETE FROM boards
      WHERE boards.id = ?;
    ", board_id])
  end 
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
  validates_presence_of :title

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates_presence_of :title

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :set_board, only:[:show, :edit, :update, :destroy]

  def index
    @boards = Board.all_boards(current_user.id)
  end

  def show
  end

  def new
    @board = current_user.boards.new()
  end

  def create
    @board = Board.create_board(current_user.id, board_params)
    redirect_to boards_path
  end

  def edit
  end

  def update
    Board.update_board(@board.id, board_params)
    redirect_to boards_path
  end

  def destroy
    Board.delete_board(@board.id)
    redirect_to boards_path
  end

  private def set_board
    @board = Board.single_board(current_user.id, params[:id])
  end

  def board_params
    params.require(:board).permit(:title)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only:[:show, :edit, :update, :destroy]
  
  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new()
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to board_lists_path(@board)
    else 
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to board_lists_path(@board)
    else
      render :edit 
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only:[:show, :edit, :update, :destroy]
  
  def index
    @tasks = @list.tasks
  end

  def show
  end

  def edit
    render :edit
  end

  def update
    if @task.update(task_params)
      redirect_to list_tasks_path(@list)
    else
      render :edit
    end
  end

  def new
    @task = @list.tasks.new()
    render :new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_tasks_path(@list)
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to list_tasks_path(@list)
  end

  private
  
  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :not_complete, :priority)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, autofocus: true, class: "input" %>
  </div>
  <%= f.submit nil, class: "ui button green" %>
<% end %>

app/views/boards/index.html.erb
<%if @boards.length == 0%>
<h1 class = "header">Welcome <%= current_user.full_name%>!</h1>
<h3>You don't have any boards!</h3>
<h4><%=link_to "Add a new board", new_board_path%> to get started on your journey of productivity!</h4>
    <% else %>
  <hr>
  <h1 class = "header"> Viewing All Boards </h1>
  <div class = "ui cards">
<% @boards.each do |board| %>
  <div class="ui card">
    <div class="content">
          <h1 class="header"><%= board.title %></h1>
    </div>
    <div class="extra content">
      <%= link_to "View Board", board_lists_path(board), class:"ui tiny button green inverted" %>
      <%= link_to "Edit Board", edit_board_path(board), class:"ui tiny button secondary inverted" %>
      <%= link_to "Delete Board", board_path(board), method: :delete, class:"ui tiny button red inverted" %>
    </div>
  </div>
    <% end %>
  </div>    
    <% end %>
        <%# <ul style="list-style: none;"> %>

app/views/boards/new.html.erb
<h1>Create A New Board</h1>
<hr>
<%= render "form" %>

app/views/layouts/_navbar.html.erb
<div class="ui big secondary menu">
  <i class="big green tasks icon"></i>

  <% if current_user %>
    <%= link_to "All Boards", boards_path, class: "item" %>
    <%= link_to "Add New Board", new_board_path, class: "item" %>
    <div class="right menu">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"item" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardsListsTasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class = "ui container space">
  <%= render "layouts/navbar" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, autofocus: true, class: "input" %>
  </div>

  <%= f.submit nil, class: "ui button green inverted"%>
  <% end %>

app/views/lists/edit.html.erb
<h1>Edit Board</h1>
<hr>
<%= render "form" %>

app/views/lists/index.html.erb
<% if @board.lists.length == 0 %>
  <h1>You have no lists.</h1>
  <%= link_to "New List", new_board_list_path(@board), class: "ui button green inverted"%>
  <%= link_to "Back To Boards", boards_path, class: "ui button secondary inverted"%>
<% else %>
  <h1>Showing Lists for Board: <%= @board.title %> </h1>
  <%= link_to "Add Another List", new_board_list_path(@board), class: "ui button green inverted" %>
  <%= link_to "Back To Boards", boards_path, class: "ui button secondary inverted" %>
    <hr>
    <div class = "ui cards">
      <% @board.lists.each do |list| %>
        <div class="ui card">
          <div class="content">
            <h1 class ="header">
              <%= list.title.upcase %>
            </h1>
          </div>

          <div class="content">
            <div class = "ui sub header">
            Tasks
            </div>
            <div class="ui small feed">
              <div class="summary">
                <ul>
                  <% list.tasks.each do |task| %>
                    <li><%= task.title %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

          <div class="extra content">
            <%= link_to "View Tasks", list_tasks_path(list), class: "ui mini button green inverted"%>
            <%= link_to "Edit List", edit_board_list_path(@board, list), class: "ui mini button secondary inverted"%>
            <%= link_to "Delete List", board_list_path(@board, list), method: :delete, class: "ui mini button red inverted"%>
          </div>
          <div class="ui bottom attached button">
            <i class="add green icon"></i>
            <%= link_to "View or Add Tasks", list_tasks_path(list)%>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/lists/new.html.erb
<h1>Create A New List</h1>
<hr>
<%= render "form" %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@list, @task], local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, autofocus: true, class: "input" %>
  </div>
  <div class = "field">
    <%= f.label :priority %>
    <%= f.select :priority, ['Low', 'Medium', 'High'] %>
  </div>
  
  <div class = "field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "input" %>
  </div>


  <%= f.submit nil, class: "ui button green inverted"%>
  <% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<hr>
<%= render "form" %>

app/views/tasks/index.html.erb
  <% if @list.tasks.length == 0 %>
    <h1>You have no tasks.</h1>
    <%= link_to "New Task", new_list_task_path(@list), class: "ui button green inverted"%>
    <%= link_to "Back To Lists", board_lists_path(@list.board_id), class: "ui button secondary inverted"%>
  <% else %>
    <h1>Showing Tasks for List: <%= @list.title %> </h1>
    <%= link_to "Add Another Task", new_list_task_path(@list), class: "ui button green inverted" %>
    <%= link_to "Back To Lists", board_lists_path(@list.board_id), class: "ui button secondary inverted" %>
  <hr>
  <div class = "ui cards">
    <% @tasks.each do |task| %>
        <div class="ui card">
          <div class="content">
            <h1 class ="header">
            <%= task.title.upcase %>
            </h1>
            
            <% if task.priority == "High"%>
              <h5 class = "red"> High Priority </h5>
            <%elsif task.priority == "Medium"%>
              <h5 class = "orange"> Medium Priority </h5>
            <%else task.priority == "Low" %>
              <h5 class = "green"> Low Priority </h5>
            <% end %>

            <%= link_to "Back To Lists", board_lists_path(@list.board_id)%>
          </div>

          <div class="content">
            <div class="ui small feed">
                <div class="content">
                  <div class="description">
                    <%= task.description %>
                  </div>
                </div>
            </div>
          </div>
          <div class="extra content">
          <%= link_to "Edit Task", edit_list_task_path(@list, task), class: "ui mini button secondary inverted" %>
          <%= link_to "Delete Task", list_task_path(@list, task), method: :delete, class: "ui mini button red inverted" %>
          </div>
          <div class="ui bottom attached button">
          <i class="check green circle outline icon"></i>
            <%= link_to "Mark Task As Complete", list_task_path(@list, task), method: :delete%>
          </div>
        </div>
       </div>
    <% end %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Create A New Task</h1>
<hr>
<%= render "form" %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>